// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJr1bV2dRzW-8_by2HsbyvOdw3vklhLec',
    appId: '1:242977884216:android:51b16702c43ddea2db7ecd',
    messagingSenderId: '242977884216',
    projectId: 'whatsappclone-6c00b',
    databaseURL: 'https://whatsappclone-6c00b-default-rtdb.firebaseio.com',
    storageBucket: 'whatsappclone-6c00b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfKwCBM6GdLcQ7H-GNBFLE9tFA-J8OBJk',
    appId: '1:242977884216:ios:b3b92b2804ca8300db7ecd',
    messagingSenderId: '242977884216',
    projectId: 'whatsappclone-6c00b',
    databaseURL: 'https://whatsappclone-6c00b-default-rtdb.firebaseio.com',
    storageBucket: 'whatsappclone-6c00b.appspot.com',
    androidClientId: '242977884216-kscaic9j94o0rndjg3ka7ubgi28v0kae.apps.googleusercontent.com',
    iosClientId: '242977884216-ffchdordp5q9tno13djs7jk2q3h6ceai.apps.googleusercontent.com',
    iosBundleId: 'com.whatsappclone.flutter.whatsappCloneUsingFlutter',
  );
}
